name: geocoder_offline
description: Package for super-fast offline reverse geocoding.
version: 0.1.0
homepage: https://github.com/JankoLancer/geocoder_offline

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  kdtree: ^0.0.2
  csv: ^4.0.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
